### ISSUE TITLE
Add page to explain how to change the domain name of the MoodleBox

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodlebox.net#13]
For reference, files to update to do such a change:

- /etc/hostname (not mandatory)
- /etc/hosts
- /etc/nginx/sites-available/default (nginx configuration)
- /etc/dnsmasq.conf (DNS configuration, only if "home" is changed)
- /var/www/moodle/config.php (Moodle URL)
- /etc/avahi/services/moodlebox.service (mDNS configuration, change filename too)

Then:

- Update MathJax filter configuration in Moodle.
- Run the Moodle replace tool.

**Comment by martignoni** [comment]
Fixed. Closing.

**Comment by doxendine** [comment]
Hi. Thank you for the instructions. One Question for you. I tried the instructions on the following page:
https://moodlebox.net/en/help/domain-name-change/
Everything seems simple enough, but it didn't work. I could never do step 6:
Step 6: Replace Moodle URLs
Access your MoodleBox through your browser using the new address http://mybox.me/ and use the URL replacement tool at http://mybox.me/admin/tool/replace/index.php to replace URLs in the Moodle database.

However, I noticed it seems that there are a couple extra steps above:
/etc/avahi/services/moodlebox.service (mDNS configuration, change filename too)
Then:
Update MathJax filter configuration in Moodle.

Do these steps need to be done as well? Or any thoughts on why it may not have worked?
Thanks

**Comment by doxendine** [comment]
Hi. Thank you for the instructions. One question. I tried the directions here:
https://moodlebox.net/en/help/domain-name-change/
Seemed easy enough, however could not get to work at step 6. 
I see here you have a couple extra steps it seems:
/etc/avahi/services/moodlebox.service (mDNS configuration, change filename too)
Then:
Update MathJax filter configuration in Moodle.
Should these also be done? Or any thoughts as to why it didn't work?
Thanks
