### ISSUE TITLE
Is there an another way to make url multilang in gohugo ?

### ISSUE THREAD

**Issue by jonathanulco** [moodlebox/moodlebox.net#40]
i see in your template this kind of url 
`<a href="{{ .Site.LanguagePrefix }}/license" class="">{{ i18n "licenseTitle" }}</a>`

but from the seo's point of view, I'm not a fan of having an English url for pages in another language 

you would know how to call the urls via the translationKey ?

**Comment by martignoni** [comment]
I'm afraid I cannot give Hugo support here. Please ask [Hugo community](https://discourse.gohugo.io/).
