### ISSUE TITLE
The Hamburger menu does not open on smartphone

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox.net#53]
I found that the Hamburger Menu in the upper right corner does not open on my iPhone. Perhaps this happened with an update of iOS. This is a problem with every iOS browser because they all are using the same web engine. 

![8B960D80-CB1E-4C36-A3AE-B006216D8BF6](https://user-images.githubusercontent.com/27956839/185783306-3b6a1939-c321-4c15-862c-472232898df5.jpeg)

**Comment by ralf-krause** [comment]
I get the problem with the Hamburger menu also on an Android smartphone. And the problem happens in portrait and landscape mode.

**Comment by martignoni** [comment]
Confirmed.

**Comment by martignoni** [comment]
This is a regression of commit 20976279863e9a93612a038d98b895f15ea631e3.

**Comment by ralf-krause** [comment]
Great! It works fine om my iPhone.
