### ISSUE TITLE
Layout problems with smartphone 

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodlebox.net#54]
When you are using a smartphone in portrait mode you will get some layout problems with the web site https://moodlebox.net.

The column width is different for the news. (See the first screenshot)
The statements of the users are unreadable. (See the second screenshot)

I tested these views with iOS and Android. 

![90F0775C-AD91-4F05-80F9-913271F6C13D](https://user-images.githubusercontent.com/27956839/185784471-5db13a93-6536-495b-9c36-255ae2605dff.png)

![50020023-1591-4EDD-BD72-34FB28F3F511](https://user-images.githubusercontent.com/27956839/185784475-b7a9ef22-7ef4-4838-9134-ce82b8f20242.png)

**Comment by martignoni** [comment]
Blocked by issue #56.

**Comment by ralf-krause** [comment]
Great, the layout  at the top of the page looks fine now. The layout for the topic "what users say" is still not readable. 

![Uploading 13EABDFA-1E83-4BBD-ADED-8CED08D01244.png…]()

**Comment by martignoni** [comment]
Thanks for the test. I did not yet begin to work on this, just fixed #56.

**Comment by martignoni** [comment]
Fixed by 6c12119589a5228d97a8782663096a9bfe94d3e1.

**Comment by ralf-krause** [comment]
Yes, it works on my smartphone! The user comments are looking fine now. Great!
