### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by dryscord** [moodlebox/moodlebox.net#61]
The site's CSS is broken on Brave browser. `[Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)](https://brave.com/latest/)`

**Comment by martignoni** [comment]
Please be more specific. What breaks exactly?

**Comment by dryscord** [comment]
> The site's CSS

Isn't this specific? Or what else do you want? The whole site is unusable on Brave.

**Comment by martignoni** [comment]
> The whole site is unusable on Brave.

Sorry, can't reproduce with latest Brave version (which is my default browser anyway).

**Comment by dryscord** [comment]
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css' with computed SHA-384 integrity 'rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65'. The resource has been blocked.
```

**Comment by martignoni** [comment]
Still impossible to reproduce. Does the website display correctly on other browsers/devices?

**Comment by dryscord** [comment]
Test with the Local CDN extension. Figured it was the one breaking things.
